# Generated by Django 5.2.7 on 2025-12-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
