# Generated by Django 5.2.7 on 2025-12-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_remove_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
