# Generated by Django 5.2.7 on 2025-12-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
